### ISSUE TITLE
Caching errors 

### ISSUE THREAD

**Issue by Sytten** [Swatinem/rust-cache#44]
Since yesterday we started seeing those errors:
```
Warning:  Cache service responded with 400 during upload chunk.
Warning:  Cache upload failed because file read failed with EBADF: bad file descriptor, read
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:359:[31](https://github.com/caido/proxy-backend/runs/5080976100?check_suite_focus=true#step:15:31))
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
Warning:  Cache upload failed because file read failed with ESPIPE: invalid seek, read
Error: Cache upload failed because file read failed with ESPIPE: invalid seek, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:359:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```
The upload takes 5-6m but then the cache is never really reused.

**Comment by Swatinem** [comment]
Is this a reproducible error? Looks a bit like an intermittent failure to me. Though the specifics of how the cache works use the same code as the upstream `actions/cache`, so is outside of this specific action.

**Comment by Sytten** [comment]
It seems intermittent, yeah it is an upstream fault I think
