### ISSUE TITLE
Enabling Cargo sparse-registry breaks post step

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [Swatinem/rust-cache#64]
(See https://internals.rust-lang.org/t/call-for-testing-cargo-sparse-registry/16862 for the details on cargo sparse registry.)

To reproduce, enable Cargo sparse-registry:
```
env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true
```

In `Post Run Swatinem/rust-cache@v1` there is this:
```
##[debug]Evaluating condition for step: 'Post Run Swatinem/rust-cache@v1'
##[debug]Evaluating: (success() || (env.CACHE_ON_FAILURE == 'true'))
##[debug]Evaluating Or:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]=> true
##[debug]Expanded: (true || (env['CACHE_ON_FAILURE'] == 'true'))
##[debug]Result: true
##[debug]Starting: Post Run Swatinem/rust-cache@v1
##[debug]Loading inputs
##[debug]Loading env
Post job cleanup.
##[debug]followSymbolicLinks 'false'
##[debug]followSymbolicLinks 'false'
##[debug]implicitDescendants 'true'
##[debug]matchDirectories 'true'
##[debug]omitBrokenSymbolicLinks 'true'
##[debug]Search path '/home/runner/.cargo/registry/index'
Warning:  The "path" argument must be of type string. Received undefined
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Post Run Swatinem/rust-cache@v1
```

As a result, nothing is saved to the cache.

Stack trace for this exception (produced using #63):
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.dirname (path.js:1128:5)
    at getRegistryName (rust-cache/src/save.ts:64:1)
    at run (rust-cache/src/save.ts:21:1)
```

---

This happens because the file `~/.cargo/registry/index/github.com-1ecc6299db9ec823/.last-updated` expected by the action is not created when using sparse checkout. Instead, these is `~/.cargo/registry/index/index.crates.io-e139d0d48fed7772/`.

**Comment by Vlad-Shcherbina** [comment]
This is similar to #9 (also caused by some files expected by the action are missing), but it has nothing to do with containers, so I opened a separate issue.
