### ISSUE TITLE
Fail at saving the cache

### ISSUE THREAD

**Issue by bragov4ik** [Swatinem/rust-cache#77]
Cache is not being saved, debugging mode in github output is given below. 
Here is the workflow where the action is called:
https://github.com/bragov4ik/devops/actions/runs/3077934245/jobs/4973164111
```
##[debug]Evaluating condition for step: 'Post Run Swatinem/rust-cache@v1'
##[debug]Evaluating: (success() || (env.CACHE_ON_FAILURE == 'true'))
##[debug]Evaluating Or:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]=> true
##[debug]Expanded: (true || (env['CACHE_ON_FAILURE'] == 'true'))
##[debug]Result: true
##[debug]Starting: Post Run Swatinem/rust-cache@v1
##[debug]Loading inputs
##[debug]Loading env
Post job cleanup.
##[debug]followSymbolicLinks 'false'
##[debug]followSymbolicLinks 'false'
##[debug]implicitDescendants 'true'
##[debug]matchDirectories 'true'
##[debug]omitBrokenSymbolicLinks 'true'
##[debug]Search path '/home/runner/.cargo/registry/index'
Warning:  Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
    at ExecState._setResult (/home/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:3999:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:3982:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:3876:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Post Run Swatinem/rust-cache@v1
```

**Comment by Swatinem** [comment]
Interesting, it really should work. Can you update to v2 and check if that still fails?

**Comment by bragov4ik** [comment]
Running version 2 actually produced understandable error messages, for example
```Warning:  error: could not find `Cargo.toml` in `/home/runner/work/devops/devops` or any parent directory```
which makes sense since rust project is located in a subfolder.
So I fixed the problems and it seems to work well. Thank you for the suggestion :+1:
